config/routes.rb
Rails.application.routes.draw do
 
  match 'reports', to: 'reports#index', via: [:get, :post]

  get 'archives/detail/:date', to: 'archives#detail', as: 'archives'
  get 'archives/index', to: 'archives#index'

  resources :types
  resources :visitors
  resources :personals
  
  devise_for :users

  TheRoleManagementPanel::Routes.mixin(self)
  

  root 'visitors#index'
end

app/models/visitor.rb
# == Schema Information
#
# Table name: visitors
#
#  id         :integer          not null, primary key
#  time       :datetime
#  name       :string(255)
#  type_id    :integer
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#  end_time   :datetime
#

class Visitor < ActiveRecord::Base
  acts_as_paranoid
	validates :time, presence: true
	validates :name, presence: true
	validates :user, presence: true
	validates :type, presence: true

	default_scope { where("created_at > ?", DateTime.now.midnight).order(type_id: :asc) }

	before_validation :add_time, on: :create
	before_save :count_time2end
	before_update :count_time2end
	
	belongs_to :type
	belongs_to :user

	def self.as_csv
	  CSV.generate do |csv|
      csv << ["Time", "End Time", "Name", "Phone number","Administrator name", "Type"] 
      sum = 0
      all.each do |vis|
        sum += vis.type.price
        csv << [self.to_correct_date(vis.time), self.to_correct_date(vis.end_time), vis.name, vis.phone_number, vis.user.name, vis.type.name]
      end
      csv << ["\n"]
      csv << ["Summ", sum]
	  end
	end

	def self.to_correct_date(date)
		date.strftime("%d-%m-%Y %H:%M")
	end

	def self.search(search)
	  if search
	    where('lower(name) LIKE lower(?)', "%#{search}%")
	  else
	    all
	  end
	end

	protected
		def add_time
			self.time ||= DateTime.now()
		end

		def count_time2end
			last_time = Time.now().end_of_day - 7200
			e_time = self.time + self.type.time_seconds
			
			self.end_time ||= ( e_time > last_time) ? last_time : e_time			
		end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  before_action :set_visitor, only: [:show, :edit, :update, :destroy]

  require 'csv'

  def index
    if current_user.admin? || current_user.moderator?(:roles)
        @visitors = Visitor.includes(:type).search(params[:search])
    else        
        @visitors = current_user.visitors.includes(:type).search(params[:search])
    end

    @date = params[:month] ? Date.parse(params[:month]) : Date.today
    
    @types = Type.order(id: :desc)
    @c_visitors = Visitor.with_deleted.count

    respond_to do |format|
      format.html {}
      format.js   {}
      format.csv  { send_data @visitors.as_csv, filename: "visitors-#{Date.today}.csv" }
    end
  end

  def show
    respond_to do |format|
      format.html {}
      format.js {}
    end
  end

  def new
    @visitor = Visitor.new

    respond_to do |format|
      format.html {}
      format.js {}
    end
  end

  def edit
    redirect_to root_path unless current_user.admin? || current_user.moderator?
  end

  def create
    @visitor = current_user.visitors.create(visitor_params)

    if @visitor.save
      respond_to do |format|
        format.html { redirect_to visitors_path}
        format.js {}
      end
    else
      respond_to do |format|
        format.html { render "new" }
        format.js {}
      end
    end

  end

  def update
    @visitor.update(visitor_params)

    respond_to do |format|
      format.html { redirect_to root_path}
      format.js {}
    end
  end

  def destroy
    @visitor.destroy
    respond_to do |format|
      format.html { redirect_to visitors_path}
      format.js {}
    end
  end

  private
    def set_visitor
      @visitor = Visitor.find(params[:id])
    end

    def visitor_params
      params.require(:visitor).permit(:name, :phone_number, :type_id)
    end
end

app/helpers/visitors_helper.rb
module VisitorsHelper
	def color_of_type(type)
		tag("span", style: "background: #{type.color};", class: "color-box", data:{id:type.id})
	  # content_tag(:span, style: "background: #{color};", :class => "color-box")
	end
  def check_time(visitor)
    valid_date = visitor.end_time.strftime("%H:%M")
    if DateTime.now.to_i >= visitor.end_time.to_i
      content_tag(:span, valid_date, class: ["time_end"], data:{time_end: true})
    else
      valid_date
    end
  end
end

app/views/visitors/_form.html.haml
= simple_form_for @visitor, defaults: { input_html: { class: 'form-control' } } do |f|
	- if @visitor.errors.any?
		#error_explanation
			%h2= "#{pluralize(@visitor.errors.count, "error")} prohibited this visitor from being saved:"
			%ul
				- @visitor.errors.full_messages.each do |msg|
					%li= msg
	
	= f.input :name, required: true
	%br/
	= f.input :phone_number
	%br/
	= f.association :type
	%br
	= f.button :submit, class: "btn btn-primary save-submit", id:"form_save"

.pay
	%h1
		Pay:
		%span.price 100		

app/views/visitors/_visitors.html.haml
Visitors:
%span.fa.fa-users
  = @c_visitors
%table.table.table-bordered.table-small-font
  %thead
    %tr
      %th Time
      %th End Time
      %th Name
      %th Type
      %th Color
      %th Phone      
      %th Actions

  %tbody.row
    - @visitors.each do |visitor|
      %tr{data:{color:visitor.type.id}}
        %td= visitor.time.strftime("%H:%M")
        %td= check_time(visitor)
        %td= visitor.name
        %td= visitor.type.name
        %td= color_of_type(visitor.type)
        %td= visitor.phone_number        
        %td
          -if current_user.admin?
            = link_to '', edit_visitor_path(visitor), class: "fa fa-pencil" 
          %span{style:"float:rigth"}
            = link_to ' ', visitor, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "fa fa-archive"

app/views/visitors/edit.html.haml
%h1 Editing visitor

= render 'form'

= link_to 'Back', visitors_path

app/views/visitors/index.html.haml
= simple_form_for '', html: {method: :get, id: :search_form }, defaults: { input_html: { class: 'form-control'} } do |f|  
  = f.input_field :search, required:false, placeholder: "Search .... "
  %span.right
    = f.submit "search", class: "btn btn-danger"

      
%h1 Visitors
%p
  Select color:
  %ul
    - @types.each do |type|
      .smallbox= color_of_type(type)

%span.right.fa.fa-download.download
  = link_to 'Export to Excel', visitors_path(format: :csv)

#visitors
  =render 'visitors'

%span.fa.fa-user-plus
  = link_to 'New Visitor', new_visitor_path

app/views/visitors/index.js.haml
$('#visitors').html("#{escape_javascript(render 'visitors')}");

app/views/visitors/new.html.haml
.col-md-6.col-md-offset-3
	%h1 New visitor
	
	= render 'form'

	= link_to 'Back', visitors_path

app/views/visitors/show.html.haml
%p#notice= notice

%p
  %b Time:
  = @visitor.time
%p
  %b Name:
  = @visitor.name
%p
  = @visitor.type.name
%p
  %b User:
  = @visitor.user.email


= link_to 'Edit', edit_visitor_path(@visitor)
\|
= link_to 'Back', visitors_path