config/routes.rb
Rails.application.routes.draw do
 
  match 'reports', to: 'reports#index', via: [:get, :post]

  get 'archives/detail/:date', to: 'archives#detail', as: 'archives'
  get 'archives/index', to: 'archives#index'

  resources :types
  resources :visitors
  resources :personals
  
  devise_for :users

  TheRoleManagementPanel::Routes.mixin(self)
  

  root 'visitors#index'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime
#  updated_at             :datetime
#  role_id                :integer
#

class User < ActiveRecord::Base
	include TheRole::Api::User
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :visitors
  belongs_to :role
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :check_rules  

  def index
    @users = User.includes(:role)
    respond_to do |format|
      format.html {}
      format.json {@users.to_json}
    end
  end

  def show
    respond_to do |format|
      format.html {}
      format.json {@user.to_json}
    end
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      respond_to do |format|
        format.html { redirect_to users_path}
        format.js {}
      end
    else
      respond_to do |format|
        format.html { render "new" }
        format.js {}
      end
    end
  end

  def update
    if @user.update(user_params)
      respond_to do |format|
        format.html { redirect_to users_path}
        format.js {}
      end
    else
      respond_to do |format|
        format.html { render "update" }
        format.js {}
      end
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :role_id)
    end

    def check_rules
      redirect_to root_path unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= simple_form_for @user, defaults: { input_html: { class: 'form-control' } } do |f|
	- if @user.errors.any?
		#error_explanation
			%h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
			%ul
				- @user.errors.full_messages.each do |msg|
					%li= msg

	= f.input :name, required: true
	= f.input :email, required: true
	= f.input :password, required: true
	= f.association :role, collection: Role.where("id > 1"), include_blank: false
	%br
	= f.button :submit, class: "save-submit", id:"form_save"

app/views/users/_users.html.haml
%table.table.table-bordered
  %thead
    %tr
      %th Имя
      %th E-mail
      %th Роль
      %th
      %th
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= user.name
        %td= user.email
        %td= user.role.name
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Delete', user, :method => :delete, :data => { :confirm => 'Are you sure?' }
%br

app/views/users/edit.html.haml
%h1 Editing visitor

= render 'form'

= link_to 'Show', @visitor
\|
= link_to 'Back', visitors_path

app/views/users/index.html.haml
.col-md-6.col-md-offset-3
  %h1 Listing visitors

  =render 'users'

  = link_to 'New user', new_user_path

  - if current_user
    - if current_user.admin? || current_user.moderator?(:roles)
      = link_to 'TheRole Manage Panel',  admin_roles_path
    - if current_user.admin?
      = link_to 'Types', types_path

app/views/users/index.js.haml
$('#visitors').html("#{escape_javascript(render 'visitors')}");

app/views/users/new.html.haml
.col-md-6.col-md-offset-3
	%h1 New visitor

	= render 'form'

	= link_to 'Back', visitors_path

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @user.name
%p
  %b Email:
  = @user.email
%p
  %b Role:
  = @user.role.name


= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path