config/routes.rb
Rails.application.routes.draw do
 
  match 'reports', to: 'reports#index', via: [:get, :post]

  get 'archives/detail/:date', to: 'archives#detail', as: 'archives'
  get 'archives/index', to: 'archives#index'

  resources :types
  resources :visitors
  resources :personals
  
  devise_for :users

  TheRoleManagementPanel::Routes.mixin(self)
  

  root 'visitors#index'
end

app/controllers/personals_controller.rb
class PersonalsController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :check_rules  

  def index
    @users = User.includes(:role).order(id: :desc)
    respond_to do |format|
      format.html {}
      format.json {@users.to_json}
    end
  end

  def show
    respond_to do |format|
      format.html {}
      format.json {@user.to_json}
    end
  end

  def new
    @personal = User.new
  end

  def edit
  end

  def create
    @personal = User.new(user_params)
    
    if @personal.save
      respond_to do |format|
        format.html { redirect_to personals_path}
        format.js {}
      end
    else
      respond_to do |format|
        format.html { render "new" }
        format.js {}
      end
    end
  end

  def update
    if @personal.update(user_params)
      respond_to do |format|
        format.html { redirect_to personals_path}
        format.js {}
      end
    else
      respond_to do |format|
        format.html {render "edit"}
        format.js {}
      end
    end
  end

  def destroy
    @personal.destroy
    redirect_to personals_path
  end

  private
    def set_user
      @personal = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :role_id)
    end

    def check_rules
      redirect_to root_path unless current_user.admin?
    end
end

app/views/personals/_form.html.haml
= simple_form_for @personal, url: personal_path, defaults: { input_html: { class: 'form-control' } } do |f|
	- if @personal.errors.any?
		#error_explanation
			%h2= "#{pluralize(@personal.errors.count, "error")} prohibited this personal from being saved:"
			%ul
				- @personal.errors.full_messages.each do |msg|
					%li= msg

	= f.input :name, required: true
	= f.input :email, required: true
	= f.input :password, required: true
	= f.association :role, collection: Role.where("id > 1"), include_blank: false
	%br
	= f.button :submit, class: "btn btn-primary save-submit", id:"form_save"

app/views/personals/_personals.html.haml
%table.table.table-bordered
  %thead
    %tr
      %th Имя
      %th E-mail
      %th Роль
      %th
      %th
      %th

  %tbody
    - @personals.each do |persone|
      %tr
        %td= persone.name
        %td= persone.email
        %td= persone.role.name
        %td= link_to 'Show', persone
        %td= link_to 'Edit', edit_persone_path(persone)
        %td= link_to 'Delete', persone, :method => :delete, :data => { :confirm => 'Are you sure?' }
%br

app/views/personals/_users.html.haml
%table.table.table-condensed
  %thead
    %tr
      %th Name
      %th E-mail
      %th Type
      %th
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= user.name
        %td= user.email
        %td= user.role.name        
        %td= link_to ' ', edit_personal_path(user), class: "fa fa-pencil"
        %td= link_to ' ', personal_path(user), :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "fa fa-trash-o"
%br

app/views/personals/edit.html.haml
%h1 Editing visitor

= simple_form_for @personal, url: personal_path, defaults: { input_html: { class: 'form-control' } } do |f|
	- if @personal.errors.any?
		#error_explanation
			%h2= "#{pluralize(@personal.errors.count, "error")} prohibited this personal from being saved:"
			%ul
				- @personal.errors.full_messages.each do |msg|
					%li= msg

	= f.input :name, required: true
	= f.input :email, required: true
	= f.input :password, required: true
	= f.association :role, collection: Role.where("id > 1"), include_blank: false
	%br
	= f.button :submit, class: "btn btn-primary save-submit", id:"form_save"

= link_to 'Back', visitors_path

app/views/personals/index.html.haml
%h1 Listing personals

=render 'users'

%i.fa.fa-plus-circle
	= link_to 'New user', new_personal_path

app/views/personals/index.js.haml
$('#visitors').html("#{escape_javascript(render 'visitors')}");

app/views/personals/new.html.haml
%h1 New personal item

= simple_form_for @personal, url: personals_path, defaults: { input_html: { class: 'form-control' } } do |f|
	- if @personal.errors.any?
		#error_explanation
			%h2= "#{pluralize(@personal.errors.count, "error")} prohibited this personal from being saved:"
			%ul
				- @personal.errors.full_messages.each do |msg|
					%li= msg

	= f.input :name, required: true
	= f.input :email, required: true
	= f.input :password, required: true
	= f.association :role, collection: Role.where("id > 1"), include_blank: false
	%br
	= f.button :submit, class: "btn btn-primary save-submit", id:"form_save"

= link_to 'Back', visitors_path

app/views/personals/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @user.name
%p
  %b Email:
  = @user.email
%p
  %b Role:
  = @user.role.name


= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path