config/routes.rb
Rails.application.routes.draw do
 
  match 'reports', to: 'reports#index', via: [:get, :post]

  get 'archives/detail/:date', to: 'archives#detail', as: 'archives'
  get 'archives/index', to: 'archives#index'

  resources :types
  resources :visitors
  resources :personals
  
  devise_for :users

  TheRoleManagementPanel::Routes.mixin(self)
  

  root 'visitors#index'
end

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-inverse
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-2", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Coworking system", root_path, class: "navbar-brand"
    #bs-example-navbar-collapse-2.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li.active
          = link_to '', new_visitor_path, class: "fa fa-user-plus fa-2x"
        - if current_user.admin?  
          %li                   
            = link_to ' Archives',  archives_index_path, class: "fa fa-calendar"
          %li                   
            = link_to ' Personal',  personals_path, class: "fa fa-users"
          %li                   
            = link_to ' Types',  types_path, class: "fa fa-list-alt"
          %li
            = link_to ' Manage role',  admin_roles_path, class: "fa fa-cogs"
          %li
            = link_to ' Reports', reports_path, class: "fa fa-line-chart"
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to "Out", destroy_user_session_path, method: :delete, class: "fa fa-sign-out"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width", :name => "viewport"}/
    %title CoworkingSystem
    = include_gon
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true    
    = javascript_include_tag 'application', 'data-turbolinks-track' => true    
    = csrf_meta_tags    
  %body
    -if current_user
      = render "layouts/navigation"
    .col-xs-12.col-sm-8.col-sm-offset-2.col-md-8.col-md-offset-2.col-lg-8.col-lg-offset-2
      = yield
        